version: '3.8'
services:
  db:
    build: ./docker/

    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/cnf/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - ./:/usr/src
    ports:
      - 3306:3306